spring.application.name=ingestion-service

server.port=8080

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:h2:mem:retaildb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jmx.enabled=false

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
inventory.service.process.url=http://localhost:8081/inventory/process
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false
spring.thymeleaf.cache=false